[webserver]
web ansible_host=43.205.237.130 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/travelmemory-key.pem

[dbserver]
db ansible_host=10.0.2.161 ansible_user=ubuntu ansible_ssh_private_key_file=../terraform/travelmemory-key.pem ansible_ssh_common_args='-o ProxyJump=ubuntu@43.205.237.130'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
